name: Main Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: clone down repo
        uses: actions/checkout@v4
      - name: build application
        run: ci/build-app.sh
      - name: test application
        run: ci/unit-test-app.sh
      - name: upload repo
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
          include-hidden-files: true  
          
  linting:
   runs-on: ubuntu-latest
   needs: [build]
   steps:
     - name: download code
       uses: actions/download-artifact@v4
       with:
         name: code
         path: .
     - name: Run linting
       uses: super-linter/super-linter/slim@v7
       env:
         DEFAULT_BRANCH: main
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         DISABLE_ERRORS: true 
        
    
          
